apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: my-s3-bucket-oumayma2
spec:
  forProvider:
    region: us-east-2
     versioning:
      enabled: true
  providerConfigRef:
    name: default