apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: example-s3-bucket
spec:
  forProvider:
    region: us-east-2
    acl: private
    versioning:
      enabled: true
  providerConfigRef:
    name: default
