apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: my-s3-bucket-oumayma2
spec:
  forProvider:
    acl: private
    versioning:
      enabled: true
  providerConfigRef:
    name: default
    lifecycleConfiguration:
      rules:
      - id: logs
        prefix: logs/
        status: Enabled
        expirationInDays: 7
    loggingConfiguration:
      destinationBucketName: logs-bucket-crossplane
      logFilePrefix: logs/
    tags:
    - key: Name
      value: my-s3-bucket-oumayma2
    corsConfiguration:
      corsRules:
      - allowedHeaders:
        - "*"
        allowedMethods:
        - GET
        - POST
        - PUT
        allowedOrigins:
        - "*"
        exposeHeaders:
        - "ETag"
        maxAgeSeconds: 300
  deletionPolicy: Delete

